### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by python273** [OlegWock/OlegWock.github.io#2]
https://gist.github.com/python273/3e4c34327004a7a88af67ce7933d6e9c/revisions

Я б так написал

data-text сурово конечно, блоки удобнее редактировать

**Comment by OlegWock** [comment]
Спасибо за нормальный перевод, у меня с этим не очень. 

> блоки удобнее редактировать

Имеешь ввиду создать несколько div и свитчить display none/block? Да, так будет лучше наверное

**Comment by python273** [comment]
> нормальный перевод

Ну я не уверено что он прямо _нормальный_, но вроде лучше

> Имеешь ввиду создать несколько div и свитчить display none/block?

Ага, как в бутстрапе
